version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: aban_task
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=aban_task
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password

volumes:
  mysql_data:
